language: java
#jdk: openjdk14 #problems with sonar-maven-plugin
branches:
  only:
    - main
notifications:
  email:
    recipients:
      - luisenriquechavezporroa@gmail.com
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn  clean verify