language: java
jdk:
   - openjdk8
#jdk: openjdk14 #problems with sonar-maven-plugin
branches:
  only:
    - main
notifications:
  email:
    recipients:
      - luisenriquechavezporroa@gmail.com

install: mvn install
script:
  - mvn clean verify