language: java
jdk:
  - openjdk16
#jdk: openjdk14 #problems with sonar-maven-plugin
branches:
  only:
    - main
notifications:
  email:
    recipients:
      - luisenriquechavezporroa@gmail.com

      #install: true
      #-mvn install
before_install:
  -addons:
    chrome: stable
    firefox: latest

    install:
      - mvn clean install
      - wget -N https://chromedriver.storage.googleapis.com/80.0.3987.106/chromedriver_linux64.zip -P ~/
      - unzip ~/chromedriver_linux64.zip -d ~/
      - rm ~/chromedriver_linux64.zip
      - sudo mv -f ~/chromedriver /usr/local/share/
      - sudo chmod +x /usr/local/share/chromedriver
      - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
      - wget -N https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz -P ~/
      - tar -xzf ~/geckodriver-v0.26.0-linux64.tar.gz -C ~/
      - rm ~/geckodriver-v0.26.0-linux64.tar.gz
      - sudo mv -f ~/geckodriver /usr/local/share
      - sudo chmod +x /usr/local/share/geckodriver
      - sudo ln -s /usr/local/share/geckodriver /usr/local/bin/geckodriver

script:
  - mvn clean verify